### ISSUE TITLE
please add getAliasName method to the context

### ISSUE THREAD

**Issue by exp-sabhyankar** [aws/aws-lambda-java-libs#10]
Requesting to please add getAliasName method to the context  https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-core/src/main/java/com/amazonaws/services/lambda/runtime/Context.java

**Comment by msailes** [comment]
Hello,

Could you describe why this would be useful to you? What would you be using the alias name for?

Thanks,
