### ISSUE TITLE
Log4j : not able to get AWSRequestId in JsonLayout

### ISSUE THREAD

**Issue by dhwanikaneria** [aws/aws-lambda-java-libs#101]
I tried every possible way to get AWSRequestId in JSON Layout.
Example:
1.
```
 <JsonLayout>
 <KeyValuePair key="AWSRequestId" value="%X{AWSRequestId}"/>
</JsonLayout>
```
2. 
`<KeyValuePair key="AWSRequestId" value="${X:AWSRequestId}"/>`

It would be great, if you show me correct way to get AWSRequestId.

**Comment by prameshbhattarai** [comment]
As we were using Log4j for logging on our AWS Java Lambda, we fixed this issue by adding **AWSRequestId** in Log4j **ThreadContext** in our abstract Lambda handler class. So whenever lambda function gets triggers, it add **AWSRequestId** in **ThreadContext** map and is available while printing log.

Here is a link about Log4j ThreadContext map -> https://logging.apache.org/log4j/2.x/manual/thread-context.html

```
/**
 * All the lambda handler class should extend this class.
 */
public abstract class AbstractEventHandler<I, O> implements RequestHandler<I, O> {

    @Override
    public O handleRequest(I input, Context context) {
        // As in our implementation, we have created child threads from our main thread
        // but in child threads, Thread ContextMap might not be available.
        // so we need to pass this by setting Log4j property
        // isThreadContextMapInheritable to true.
        System.setProperty("isThreadContextMapInheritable", "true");

        // Adding AWSRequestId in ThreadContext map.
        ThreadContext.put("AWSRequestId", context.getAwsRequestId());
        return requestHandler(input, context);
    }

    abstract protected O requestHandler(I input, Context context);
}
```

**Comment by harryurban** [comment]
@dhwanikaneria I assume you tried it only locally, right?
With the following configuration it works for us, but only when the code really is running in AWS Lambda environment. My local invocations of my Handler with a Fake implementation of the `Context.class`  didn't trigger the `LambdaAppender` included in `com.amazonaws:aws-lambda-java-log4j2`, so because of the missing value I came to a similar solution like you did, which I removed again after eventually testing it in a real lambda execution.

```
<Configuration packages="com.amazonaws.services.lambda.runtime.log4j2">
  <Properties>
    <Property name="AWSRequestId"/> // this default value omits the field in logs when not set
  </Properties>
<Appenders>
    <Lambda name="LambdaHandler">
      <JsonLayout>
        <KeyValuePair key="awsRequestId" value="$${ctx:AWSRequestId}"/>
      </JsonLayout>
    </Lambda>
</Appenders>
<Loggers>
    <Root level="warn">
      <AppenderRef ref="LambdaHandler"/>
    </Root>
  </Loggers>
</Configuration>
```

**Comment by msailes** [comment]
Hi @dhwanikaneria,

Did you resolve this issue?

Thanks,

Mark

**Comment by jsitu777** [comment]
what if you want to hide the $${ctx:AWSRequestId} shown in the message when the field is not set? do you do $${ctx:AWSRequestId:-blank} ? @harryherbig
