### ISSUE TITLE
Please add Destinations Invocation Records

### ISSUE THREAD

**Issue by mikebroberts** [aws/aws-lambda-java-libs#104]
Per https://docs.aws.amazon.com/lambda/latest/dg/invocation-async.html#invocation-async-destinations

Thanks!

Mike

**Comment by msailes** [comment]
Hi Mike, could you tell us a bit more about what you'd like to see?

**Comment by mikebroberts** [comment]
Going back a little now so my memory is fuzzy ... but I think what I'd like is to be able to create Java Lambda functions that can act as Destinations. And therefore "AWS Lambda Java Events" updated to support this scenario. IIRC I tried doing this manually with my own Jackson objects and hit some problems.

**Comment by msailes** [comment]
Thanks for taking the time to explain it, I'll have a look into it.

**Comment by carlzogh** [comment]
Hey @keinproblem,

`LambdaDestinationEvent ` has been added to the `aws-lambda-java-events` library and released as part of version `3.3.0` (ref: https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-events/RELEASE.CHANGELOG.md).

It is now available to download from Maven https://search.maven.org/artifact/com.amazonaws/aws-lambda-java-events/3.3.0/jar

Thanks for bringing this up!
