### ISSUE TITLE
Feature request - trigger events for Connect in "aws-lambda-java-events"

### ISSUE THREAD

**Issue by purlaksh** [aws/aws-lambda-java-libs#106]
There are no off the shelf trigger events for Connect in "aws-lambda-java-events"

Customer needs assistance in building java code for lambda events associating with connect which is currently not available.

**Comment by msailes** [comment]
Hi Purlaksh, 

We're looking into adding this event to the library.

Thanks,

**Comment by carlzogh** [comment]
Hey @purlaksh,

`ConnectEvent ` has been added to the `aws-lambda-java-events` library and released as part of version `3.3.0` (ref: https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-events/RELEASE.CHANGELOG.md).

It is now available to download from Maven https://search.maven.org/artifact/com.amazonaws/aws-lambda-java-events/3.3.0/jar

Thanks for bringing this up!
