### ISSUE TITLE
Cannot serialize into SQSEvent- NPE on all accessors

### ISSUE THREAD

**Issue by rickbhardwaj** [aws/aws-lambda-java-libs#107]
I am trying to deserialize the default SQS test vent into an SQSEvent class, but a NPE is always thrown when I try to access the records. Looking through previous issues, others noted this and pointed to a case sensitivity issue in jackson. Any progress on this issue?

Here's my dependencies:

```
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-lambda-java-core</artifactId>
            <version>1.2.0</version>
        </dependency>
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-lambda-java-events</artifactId>
            <version>2.2.7</version>
        </dependency>
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-sqs</artifactId>
            <version>1.11.708</version>
        </dependency>

```

The event:

```
{
  "Records": [
    {
      "messageId": "19dd0b57-b21e-4ac1-bd88-01bbb068cb78",
      "receiptHandle": "MessageReceiptHandle",
      "body": "Hello from SQS!",
      "attributes": {
        "ApproximateReceiveCount": "1",
        "SentTimestamp": "1523232000000",
        "SenderId": "123456789012",
        "ApproximateFirstReceiveTimestamp": "1523232000001"
      },
      "messageAttributes": {},
      "md5OfBody": "7b270e59b47ff90a553787216d55d91d",
      "eventSource": "aws:sqs",
      "eventSourceARN": "arn:{partition}:sqs:{region}:123456789012:MyQueue",
      "awsRegion": "{region}"
    }
  ]
}
```

The accessor code:

```
public class App implements RequestHandler<SQSEvent, Object> {

    public Object handleRequest(final SQSEvent input, final Context context) {

        System.out.println(input.getRecords());  //<--- this line throws the exception

        Map<String, String> headers = new HashMap<>();
        headers.put("Content-Type", "application/json");
        headers.put("X-Custom-Header", "application/json");

        return new GatewayResponse("SUCCESS", headers, 200);
    }
}
```

And the exception:
```
Running helloworld.AppTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.059 sec <<< FAILURE!
successfulResponse(helloworld.AppTest)  Time elapsed: 0.007 sec  <<< ERROR!
java.lang.NullPointerException
	at helloworld.App.handleRequest(App.java:22)
	at helloworld.AppTest.successfulResponse(AppTest.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by mukhtar** [comment]
Hi, thanks for reporting the issue. 

I am not able to reproduce this using the snippet you provided when running in Lambda. From the exception, it seems you're running a unit test, can you please explain how you're running the function?

**Comment by mukhtar** [comment]
Any chance you're using a project generated using https://github.com/awslabs/aws-sam-cli-app-templates? If you're able to upload a minimal reproducer of the whole project that would be useful. The Lambda Java runtime has custom marshalling which differs from the (de)serializer used in `aws-sam-cli-app-templates`.

**Comment by rickbhardwaj** [comment]
I'm using the project generated by IntelliJ's AWS Toolkit, which may use that template? I'm running the unit test via sam local. I'll zip the project and upload it soon.

**Comment by msailes** [comment]
Hi Rick, 

Is this issue still a problem? Do you have a copy of the project we can look at to help?

Thanks,

**Comment by rickbhardwaj** [comment]
Hi,

Sorry I no longer have access to this code- it was on a project at my previous company. I do remember rolling my own Jackson serializer that ignored case sensitivity to get around this. But unfortunately I can't share anymore.
