### ISSUE TITLE
A potentially (very) interesting feature: Context.getNumberOfRetries()

### ISSUE THREAD

**Issue by hatimk** [aws/aws-lambda-java-libs#11]
Hi,

After doing some research on the internet, it seems that a few Lambda-java users (including me) are worried about the fact that there is no way to control its behaviour when an exception is raised, especially when Kinesis or DynamoDB streams are specified as triggers. Apparently, these streams last for 24 hours and a problematic code is doomed to be executed by lambda again and again during this whole period. Please correct me if I am wrong about that (some posts talk about a "context.succeed" trick but they seem to be speaking NodeJS or Python and I prefer Java).

To my view, a "simple" solution would be to have access to the number of times that a Lambda function has been executed again as a retry (After an exception...): some sort of Context.getNumberOfRetries(). This would easily make it possible for developers to implement behaviours like "Don't try to execute again after an exception", or "You can perform 3 retrials and then forget about it, it is problematic and it won't work, you will just keep billing me for no reason...".

Please let me know what you think.

Regards,

**Comment by msailes** [comment]
Hi Hatim,

AWS Lambda Destinations looks to solve this problem. You can learn more about this feature on our blog post - https://aws.amazon.com/blogs/compute/introducing-aws-lambda-destinations/

Thanks,
