### ISSUE TITLE
Support for "result" field in KinesisFirehoseEvent.Record

### ISSUE THREAD

**Issue by dyang108** [aws/aws-lambda-java-libs#112]
In creating a Lambda transform function for Kinesis firehose, there's this in the docs:

> result
The status of the data transformation of the record. The possible values are: Ok (the record was transformed successfully), Dropped (the record was dropped intentionally by your processing logic), and ProcessingFailed (the record could not be transformed). If a record has a status of Ok or Dropped, Kinesis Data Firehose considers it successfully processed. Otherwise, Kinesis Data Firehose considers it unsuccessfully processed.

yet the Record object [here](https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/KinesisFirehoseEvent.java#L38) does not have a "result" field, rendering the wrapper class  not really usable for the lambda transformation

**Comment by msailes** [comment]
Hi Derick,

I think the class you're looking for is [KinesisAnalyticsInputPreprocessingResponse.java](https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/KinesisAnalyticsInputPreprocessingResponse.java)

Thanks,
