### ISSUE TITLE
How to invoke Nodejs lambda from Java based Lambda

### ISSUE THREAD

**Issue by rampatina** [aws/aws-lambda-java-libs#119]
Hi, I was trying to invoke Nodejs based lambda from Java-Based lambda. It is invoking the lambda but the payload is not being sent to Nodejs based lambda.
Here is the code for both lambdas:
Nodejs based lambda:
```
module.exports.handler = async (event, context, callback) => {
    console.log('event ', event) // Payload not coming here either event or context
    console.log('context', context)
    const body = JSON.parse(event);
   //Processing and return response
}
```
Java-based lambda:
```
AWSLambda client = AWSLambdaClient.builder().withRegion(region).build();
InvokeRequest().withFunctionName("nodejslambda").withPayload(payload);
InvokeResult result = client.invoke(req);
```
Your help would be greatly appricated.

**Comment by carlzogh** [comment]
Hi @rampatina, I believe your question might be better suited in https://github.com/aws/aws-sdk-java as the `AWSLambda` SDK classes live under the module [aws-java-sdk-lambda](https://github.com/aws/aws-sdk-java/tree/master/aws-java-sdk-lambda) which is not part of this GitHub project, or even in the [AWS Lambda Forum](https://forums.aws.amazon.com/forum.jspa?forumID=186&start=0) - maybe try asking this question over there?

Have you looked at the AWS Java SDK docs "[Invoking, Listing, and Deleting Lambda Functions](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/examples-lambda.html)" page? 
Here's a related forum post if that helps too [How to call an aws java lambda function from another AWS Java Lambda](https://forums.aws.amazon.com/thread.jspa?messageID=713501)

Another place you could look is StackOverflow - here's a post I found that has some good suggestions: [How to call an aws java lambda function from another AWS Java Lambda function when both are in same account, same region](https://stackoverflow.com/questions/36483042/how-to-call-an-aws-java-lambda-function-from-another-aws-java-lambda-function-wh)

I hope this helps! 
Closing issue as unrelated to project
