### ISSUE TITLE
AWS SDK has old version of lambda-core.

### ISSUE THREAD

**Issue by GitTom** [aws/aws-lambda-java-libs#12]
In order to use Lambda I installed the AWS SDK via the Eclipse update site.  This appears to have given me an update-to-date SDK, but with an old version of lambda-core (and different then if I used maven).

My SDK plug-in path for the lamda-core library is:

<My Eclipse>\plugins\com.amazonaws.eclipse.lambda_1.0.0.v201603160054\lambda-runtime-jar\aws-lambda-java-core-1.0.0.jar

So I've got lambda 1.0.0 and core 1.0.0 (but events v1.1) in my 2016-03-16 plug-in.

Checking maven I see that core was updated to 1.1 on 2015-10-07.

http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.amazonaws%22%20AND%20a%3A%22aws-lambda-java-core%22

I guess this is a problem with the AWS SDK getting updated on the Eclipse update site?

**Comment by nicholasparks** [comment]
concur observation

**Comment by bmoffatt** [comment]
If this is still an issue. https://github.com/aws/aws-toolkit-eclipse may be the right place to followup.
