### ISSUE TITLE
Stop using version ranges for dependencies

### ISSUE THREAD

**Issue by petehayes** [aws/aws-lambda-java-libs#13]
I think it is generally bad practice to use version ranges (in this project's case open ended one) for dependencies as it triggers build tools to keep going back to the repository to look for a more recent version.  

My project recently broke because of this as a new version of the AWS libraries came out on Friday that removed the json.org library.  Since we also use the lambda-java-events library, builds started immediately consuming it.  Can you lock down the dependency to a specific version?

**Comment by bmoffatt** [comment]
You can now use 1.2.1 https://github.com/aws/aws-lambda-java-libs/commit/617af8467230bf78a486316db8d4591f7c3ae75e or 1.3.0 https://github.com/aws/aws-lambda-java-libs/commit/65ef84f630638a149fab6504d938d234eef0da4a

**Comment by petehayes** [comment]
Thanks!
