### ISSUE TITLE
Add support for CloudFormation custom resource request/response

### ISSUE THREAD

**Issue by DixonDs** [aws/aws-lambda-java-libs#137]
As described in:
* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/crpg-ref-requests.html
* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/crpg-ref-responses.html

**Comment by msailes** [comment]
examples:

https://docs.aws.amazon.com/lambda/latest/dg/services-cloudformation.html

**Comment by adworacz** [comment]
Literally writing a custom resource Lambda as we speak and I was hoping to see this library supporting the event type... Settling for just +1'ing this issue.

**Comment by carlzogh** [comment]
Hey @DixonDs and @adworacz,

`CloudFormationCustomResourceEvent ` has been added to the `aws-lambda-java-events` library and released as part of version `3.3.0` (ref: https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-events/RELEASE.CHANGELOG.md).

It is now available to download from Maven https://search.maven.org/artifact/com.amazonaws/aws-lambda-java-events/3.3.0/jar

Thanks for bringing this up!
