### ISSUE TITLE
Support Cloudwatch Embedded Metrics Format

### ISSUE THREAD

**Issue by dmccorm2** [aws/aws-lambda-java-libs#147]
Support Cloudwatch Embedded Metrics format, similar to: https://github.com/awslabs/aws-embedded-metrics-node

Specification: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Embedded_Metric_Format_Specification.html

I still need to check feasibility, but looking into: using Log4j2 Event Logging, Markers, Custom Appenders, Layouts, and Filters as possible ways to do this.

**Comment by yaozhaoy** [comment]
Cloudwatch team is working a java sdk for EMF. The target date is 2020/09/18. Stay tuned for the release.
