### ISSUE TITLE
Cognito Authorizer with APIGatewayV2HTTPEvent

### ISSUE THREAD

**Issue by wheerd** [aws/aws-lambda-java-libs#148]
With the new `APIGatewayV2HTTPEvent`, `requestContext.authorizer.claims` is missing/not mapped. This prevents us updating to the new model and hence version 3.1.0, because we need the claims from Cognito for authorization. The current model only exposes `requestContext.authorizer.jwt.claims`, which is not the path used by the Cognito authorizer.

It would be great, if that can be added to this model also, because it is not only relevant for websocket integration, but for normal HTTP integration also. The same applies to `multiValueQueryStringParameters` also which is not available in the new model.

Do you need some example code? Would you like me to submit a PR?

**Comment by msailes** [comment]
Hi Manuel,

A pull request would be great! 

Thanks,

**Comment by wheerd** [comment]
I just found out that apparently we are actually using the V1 integration, but we were using it with the V2 models. So I don't think there is a need for changing the model after all, we will just use the V1 model for now (and see how things work when we switch to V2).
