### ISSUE TITLE
v2 Event request/response classes are not available in v3.0.0

### ISSUE THREAD

**Issue by avanathan** [aws/aws-lambda-java-libs#153]
I'm using this dependency in maven,

```xml
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-lambda-java-events</artifactId>
            <version>3.0.0</version>
        </dependency>
```
But still I am unable to find classes`APIGatewayV2HTTPEvent` and `APIGatewayV2HTTPResponse` in the jar, but I see them in source repo. May be new build hasn't gone to maven public repo?

**Comment by msailes** [comment]
Hi Arun,

I'll check with the team if there needs to be any adjustment to the documents. These classes are available in the next version '3.1.0'

        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-lambda-java-events</artifactId>
            <version>3.1.0</version>
        </dependency>

Thanks,

Mark
