### ISSUE TITLE
Missing public methods for APIGatewayV2HTTPEvent and APIGatewayV2HTTPResponse

### ISSUE THREAD

**Issue by sigonzal3** [aws/aws-lambda-java-libs#157]
## Issue

I noticed that[ APIGatewayV2HTTPEvent](https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/APIGatewayV2HTTPEvent.java#L28) and [APIGatewayV2HTTPResponse](https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/APIGatewayV2HTTPEvent.java#L28) are the only two classes from the APIGateway* family that doesn't have public methods implemented.

Is this intended?

## Problem

* APIGatewayV2HTTPEvent doesn't have public methods for accessing model data once a request is received.
* APIGatewayV2HTTPResponse doesn't have public constructors or setters for creating a response.

Using APIGatewayProxy* object isn't a solution for me, since I'm already using an API Gateway's API in HTTP mode. Using a Map is a quick solution for now, but I'm looking for something more type safe. Changing language from Java from something more dynamic isn't feasible.

## Solution

All other APIGateway* classes has similar methods implemented and is easy to imitate their design. I can submit a PR for correcting this, but need clarification from the team before proceeding.

## Reference

See:
* [APIGatewayProxyRequestEvent](https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/APIGatewayProxyRequestEvent.java#L10)
* [APIGatewayProxyResponseEvent](https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/APIGatewayProxyResponseEvent.java#L9)
* [APIGatewayV2WebSocketEvent](https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/APIGatewayV2WebSocketEvent.java#L11)
* [APIGatewayV2WebSocketResponse](https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/APIGatewayV2WebSocketResponse.java#L9)

**Comment by carlzogh** [comment]
Hey @sigonzal3 

We have recently started using [Lombok](https://projectlombok.org/) annotations for code generation during compile time. By looking at the source code you won't be able to spot the public methods you're looking for, as we have replaced most of the boilerplate code with Lombok annotations.

Getters, setters, and other public methods are added in via the [`@Data`](https://projectlombok.org/features/Data) annotation (eg. https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/APIGatewayV2HTTPEvent.java#L26)

When you add the `aws-lambda-java-events` library to your `pom.xml` file, Maven will grab the compiled code which should have these methods available for consumers to use.

Please let us know if you're having trouble with this or if you have further questions - thank you!

**Comment by sigonzal3** [comment]
Hello @carlzogh 

Thanks for the response. I didn't understood the annotations until now. That clarifies a lot.

The Lombok project already provides documentation for both [Gradle](https://projectlombok.org/setup/gradle) and [Maven](https://projectlombok.org/setup/maven) integrations. I will be testing my Lambda and let you know if anything arises.

Few additional questions:
* Should the README.md be updated to reflect this dependency and compilation steps? Do you want me to submit a PR for those changes?
* Should the [sample projects](https://github.com/awsdocs/aws-lambda-developer-guide/tree/master/sample-apps) be updated too? Not sure if that repo is owned by another Amazon team and needs a separate issue to be created.

**Comment by carlzogh** [comment]
Hey @sigonzal3, glad this helped.

There is no requirement for consumers to use Lombok, as they will be consuming the compiled library after the code from annotations is generated. 
Thus, I don't think the README or sample projects need to be updated as the code stays the same from a consumer's point of view. 

However it may be useful to add a `DEVELOPMENT.md` file that describes how one would set up their local environment and IDE for development and contributions to the library (this could link to Lombok documentation eg. [IntelliJ plugin](https://projectlombok.org/setup/intellij))

Thanks for bringing this up and I hope this helps clear the confusion!
