### ISSUE TITLE
Proxy Lambda input and output format

### ISSUE THREAD

**Issue by sihil** [aws/aws-lambda-java-libs#17]
It would be great to have objects that match up with the input and output formats documented at http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-set-up-simple-proxy.html#api-gateway-simple-proxy-for-lambda-input-format

**Comment by statelessness** [comment]
+1

**Comment by alsanrum** [comment]
+1

**Comment by brackxm** [comment]
see https://github.com/awslabs/aws-serverless-java-container/tree/master/aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/model

**Comment by asuresh8** [comment]
Added
