### ISSUE TITLE
Add S3 Batch Operations Request and Response Models

### ISSUE THREAD

**Issue by david-kingsbury-bah** [aws/aws-lambda-java-libs#177]
S3 Batch Operations can invoke a Lambda written in Java. This method of Lambda invocation uses special request and response models. A developer is likely to model the request and response data in Java based on the [batch-ops-invoke-lambda documentation](https://docs.aws.amazon.com/AmazonS3/latest/dev/batch-ops-invoke-lambda.html#batch-ops-invoke-lambda-custom-functions-request).

We could include the Request and Response models in this library. We could even add a little bit of logic to help create the Response model, because most of its data is derived from the Request.

Something like:
```
com.amazonaws.services.lambda.runtime.events.S3BatchOpRequest
com.amazonaws.services.lambda.runtime.events.S3BatchOpResponse
```

**Comment by msailes** [comment]
Hi David, 

I'll look into this.

**Comment by david-kingsbury-bah** [comment]
I was thinking about opening a PR for this issue with some classes that I've already made and tested successfully. I'll see if I can get to that today.

**Comment by msailes** [comment]
That would be great.

This is what I've made, but I haven't had chance to test it yet.

https://github.com/aws/aws-lambda-java-libs/pull/179

Mark

**Comment by david-kingsbury-bah** [comment]
Awesome; testing your branch now.
