### ISSUE TITLE
Does JSON Jackson Serialiser work with Event classes?

### ISSUE THREAD

**Issue by lukepopp** [aws/aws-lambda-java-libs#178]
I'm using Micronaut to build my Java Lambda functions and I can't seem to get the events in this lib to serialise and deserialise correctly to json with Jackson.  Do we need to continue to use the old SDK?  For example, S3:

groupId=com.amazonaws
artifactId=aws-java-sdk-s3

com.amazonaws.services.s3.event.S3EventNotification

**Comment by msailes** [comment]
Hi Luke, 

Can you provide any more detail? Errors, what you're trying to do, what code isn't working.

Thanks,

**Comment by jeromevdl** [comment]
Events are available in [aws-lambda-java-events](https://github.com/aws/aws-lambda-java-libs/tree/master/aws-lambda-java-events). Using one of these events in the handler should work on Lambda without jackson (the Java Lambda Runtime will do the deserialisation).
If you mean locally, for example to test you function, you cannot simply (de)serialize an event with Jackson. But we recently released [aws-lambda-java-serialization](https://github.com/aws/aws-lambda-java-libs/tree/master/aws-lambda-java-serialization) to do it, and event simpler, you can use [aws-lambda-java-tests](https://github.com/aws/aws-lambda-java-libs/tree/master/aws-lambda-java-tests).
