### ISSUE TITLE
[Feature Request] Introduce the concept of Lambda handler request handler chain

### ISSUE THREAD

**Issue by humanzz** [aws/aws-lambda-java-libs#180]
This library has 2 base Lambda handlers at 
- [RequestStreamHandler](https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-core/src/main/java/com/amazonaws/services/lambda/runtime/RequestStreamHandler.java)
- [RequestHandler](https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-core/src/main/java/com/amazonaws/services/lambda/runtime/RequestHandler.java)

Looking to use more Lambda-related features from AWS and some logging related features in a project I'm working on, that made me think that one uniform way to solve all of them would be for the base handlers to have the concept of a request handler chain where each request handler has before/after methods that are invoked and wrap the defined handler method. This is a pattern that's used extensively in request/response services/clients.

The use cases I've recently come across which are triggering this suggestion
1. CodeGuru Profiler (https://docs.aws.amazon.com/codeguru/latest/profiler-ug/setting-up-lambda.html): their solution to initialize the profiler and to send profiling information is to provide new base handlers in a new package that extend the base handlers defined here. 
2. Aws Sdk v2 service client metrics to CloudWatch: See the discussion on https://github.com/aws/aws-sdk-java-v2/issues/2068 regarding how to batch/aggregate/emit metrics efficiently
3. Similar problems can be solved with custom business metrics emitted as part of a Lambda request
4. Similar problems can be solved with using log4j and trying to set additional attributes to MDC (in a project I'm working on we wrap each request with code that sets some properties in MDC and then clear them in the end of the request)

**Comment by msailes** [comment]
Hi Ahmed,

I think a lot of the points you've raised are being worked on with the Lambda Powertools project.

https://github.com/awslabs/aws-lambda-powertools-java

Thanks,

Mark

**Comment by humanzz** [comment]
Hi Mark,

Powertools seems really interesting and I did not know about it. I'll have a look into it.

**Comment by humanzz** [comment]
Thanks a lot Mark. I think this issue is no not needed - at least as I look into Powertools.
I'll go ahead and close it, and if I still think there's merit to it, I'll reopen it or open a new one after having a proper look into Powertools
