### ISSUE TITLE
No conversion to com.amazonaws.services.dynamodbv2.model.AttributeValue

### ISSUE THREAD

**Issue by jente-peeraer-cloudway** [aws/aws-lambda-java-libs#182]
While the 'aws-lambda-java-events-sdk-transformer' module provides a convenience method to convert a dynamodb stream event to the new SDK AttributeValue (software.amazon.awssdk.services.dynamodb.model.AttributeValue), there is no such method for the original SDK AttributeValue (com.amazonaws.services.dynamodbv2.model.AttributeValue).

**Comment by jente-peeraer-cloudway** [comment]
See PR #183

**Comment by carlzogh** [comment]
Hey @jente-peeraer-cloudway - thanks for reaching out.

This is now released in `aws-lambda-java-events-sdk-transformer` version `3.0.0`

**Comment by jente-peeraer-cloudway** [comment]
I've added a comment to the `DynamodbAttributeValueTransformer`, the `toAttributeValueMapV1` should be public as well I believe, since what you get from a `KinesisEvent.KinesisEventRecord` is an old and a new image each as a Map of AttributeValues
