### ISSUE TITLE
Omitting the Context object from handler's method signature

### ISSUE THREAD

**Issue by davidsawyer** [aws/aws-lambda-java-libs#21]
Not totally sure is this is the right place to note this documentation issue, but the following sentence can be seen on this page: http://docs.aws.amazon.com/lambda/latest/dg/java-programming-model-handler-types.html

![screen shot 2017-04-27 at 3 57 54 pm](https://cloud.githubusercontent.com/assets/724087/25501980/c6479e0a-2b62-11e7-8812-44e8c88ba8ab.png)

When I went to compile my code with the `Context` object removed from my handler's method signature, I got the following error message:

`Can't have an abstract method in a non-abstract class. The class 'MyHandlerClass' must be declared abstract or the method 'java.lang.Object handleRequest(java.lang.Object, com.amazonaws.services.lambda.runtime.Context)' must be implemented.`

So I looked at the interface definition [here](https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-core/src/main/java/com/amazonaws/services/lambda/runtime/RequestHandler.java#L20), which confirmed that the `Context` param is actually *not* optional.

Just wanted to give you a heads up about this piece of documentation.

**Comment by bmoffatt** [comment]
Thanks for the feedback. You can always submit feedback on the docs directly in the bottom of the page.

Implementing the RequestHandler interface is optional, And this is called out in the docs, but I see how the given sample might be misleading.
