### ISSUE TITLE
Add ObjectMapper for different event types for testing

### ISSUE THREAD

**Issue by zhangzhx** [aws/aws-lambda-java-libs#22]
A lot times, I want to write unit test to deserialize different events, but have problems by using the default ObjectMapper. It would be great to expose the deserialization APIs for different Events.

**Comment by galbash** [comment]
+1 on this one. I actually want to be able to deserialize an event now, and I am not sure how to approach this (since the events don't declare a `@JsonCreator`). @zhangzhx did you find a workaround for the meantime?

**Comment by jeromevdl** [comment]
Please have a look to a newly released library, built to help testing with correct deserialization of events: [aws-lambda-java-tests](https://github.com/aws/aws-lambda-java-libs/tree/master/aws-lambda-java-tests)
