### ISSUE TITLE
APIGatewayV2HTTPEvent class: Body field starts with uppercase but other events have it in lowercase

### ISSUE THREAD

**Issue by a0shvedov** [aws/aws-lambda-java-libs#221]
APIGatewayV2HTTPEvent class: Body field starts with uppercase but other events have it in lowercase.

https://github.com/aws/aws-lambda-java-libs/blob/c491aa244ce5204bee290d5a0a345b2dcc96319d/aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/APIGatewayV2HTTPEvent.java#L38

**Comment by tortru** [comment]
This also leads to body content missing when de-serializing APIGatewayV2HTTPEvent using gson. For example in custom Lambda runtimes for GraalVM.

**Comment by msailes** [comment]
fixed in v3.9.0
