### ISSUE TITLE
Missing multiValueHeaders in APIGatewayProxyResponseEvent

### ISSUE THREAD

**Issue by dforsl** [aws/aws-lambda-java-libs#227]
Hi,

I'm missing `multiValueHeaders` in `com.amazonaws.services.lambda.runtime.events.APIGatewayProxyResponseEvent`, It makes it somewhat cumbersome when one eg. wants to set multiple cookies with "non-compatible" properties that require separate header entries. To work around it, we currently have to return custom objects instead that where we set `multiValueHeaders` - would be great if we didn't have to!
 
`com.amazonaws.services.lambda.runtime.events.APIGatewayProxyRequestEvent` already supports it.

Thanks,
Daniel

**Comment by msailes** [comment]
PR https://github.com/aws/aws-lambda-java-libs/pull/228

**Comment by msailes** [comment]
This has been released in version 3.8.0
