### ISSUE TITLE
There should be a way of figuring out which user principal deleted record

### ISSUE THREAD

**Issue by minamti** [aws/aws-lambda-java-libs#23]
After adding TTL to dynamodb, aws-lambda-java-events needs to be updated to let the lambda app find out which userPrincipal deleted the record.

**Comment by msailes** [comment]
Hello,

I believe this is now included in the DynamoDB model linked below.

https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/models/dynamodb/Identity.java

As described in the documentation:

https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/time-to-live-ttl-streams.html
