### ISSUE TITLE
fields missing in APIGatewayV2WebSocketEvent object methods

### ISSUE THREAD

**Issue by brackxm** [aws/aws-lambda-java-libs#239]
the equals, hashCode, and toString methods of APIGatewayV2WebSocketEvent are only based on 3 iso all fields

https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/APIGatewayV2WebSocketEvent.java#L665

**Comment by msailes** [comment]
fixed in v3.9.0
