### ISSUE TITLE
KinesisEventRecord#toString method incorrectly prints eventSourceARN twice

### ISSUE THREAD

**Issue by scottmk** [aws/aws-lambda-java-libs#244]
[com.amazonaws.services.lambda.runtime.events.KinesisEvent.KinesisEventRecord#toString](https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/KinesisEvent.java#L318-L321) checks if `eventVersion` is `null` and then prints `eventSourceARN` a second time. 

Not only does this mean `eventVersion` is missing from the string representation, but if `eventSourceARN` is `null`, `toString` will always throw a `NullPointerException`.

**Comment by msailes** [comment]
Thank you!

**Comment by msailes** [comment]
Fixed in v3.9.0

https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-events/RELEASE.CHANGELOG.md
