### ISSUE TITLE
principalOrgId field missing from APIGatewayProxyRequestEvent

### ISSUE THREAD

**Issue by paulsgamzn** [aws/aws-lambda-java-libs#246]
API Gateway defines a [context variable](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-mapping-template-reference.html#context-variable-reference) `$context.identity.principalOrgId`.  This is missing in the java data model: https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/APIGatewayProxyRequestEvent.java#L429.

In the json passed from APIGW, this is an optional field within the `RequestIdentity` object.

**Comment by msailes** [comment]
@paulsgamzn would you be able to test this updated event?

**Comment by msailes** [comment]
released in 3.9.0

https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-events/RELEASE.CHANGELOG.md
