### ISSUE TITLE
ability to use several of these events in a single lambda

### ISSUE THREAD

**Issue by cckumarr** [aws/aws-lambda-java-libs#25]
probably adding a interface over all these events could help, so that we can use the aws-lambda-events out of the box

**Comment by asuresh8** [comment]
Can you elaborate on this use case? 

The `RequestHandler<Input, Output>` programming model intentionally does not support this kind of generic input. Obviously you could use Object, but at that point, you are better off using the `RequestStreamHandler` programming model.

Also, interface is not an appropriate grouping of java events as these event models do not share any methods that would justify an interface definition.
