### ISSUE TITLE
CloudFormationCustomResourceEvent is not serializing response URL correctly

### ISSUE THREAD

**Issue by Gtofig** [aws/aws-lambda-java-libs#253]
According to https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/crpg-ref-requests.html, response URL should be capitalized as "ResponseURL", which does not match capitalization in https://github.com/aws/aws-lambda-java-libs/blob/3ab22135a35c7ae2c52e062acf6cf5202af434a4/aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/CloudFormationCustomResourceEvent.java#L42

This is breaking serialization, and causes responseURL to be null instead of an actual value.

The fix for this would be to use @JsonProperty annotation on each field to match casing to the one in the docs

**Comment by msailes** [comment]
Hi @Gtofig 

Are you finding this problem in local testing or running on AWS Lambda?

Thanks,

Mark

**Comment by Gtofig** [comment]
Running on AWS Lambda.

**Comment by msailes** [comment]
Is it possible for you to share your handler function? removing anything sensitive of course.

**Comment by Gtofig** [comment]
FYI, here is the actual request that my custom resource lambda is receiving. As you can see, the casing is matching the one in the docs: 
```js
{
  "RequestType": "Create",
  "ServiceToken": "<redacted>",
  "ResponseURL": "<redacted>",
  "StackId": "<redacted>",
  "RequestId": "<redacted>",
  "LogicalResourceId": "<redacted>",
  "ResourceType": "AWS::CloudFormation::CustomResource",
  "ResourceProperties": {
    "ServiceToken": "<redacted>"
  }
}
```

**Comment by Gtofig** [comment]
The handler starts like this:
```java
  @Override
  public Void handleRequest(Map<String, Object> request, Context context) {
    log.info("Full request = {}", Json.asString(request));
    CloudFormationCustomResourceEvent customResourceRequest =
        Json.readQuietly(Json.asString(request), CloudFormationCustomResourceEvent.class);
    // The rest is not important, because at this point the customResourceRequest.getResponseUrl() returns null
  }
```

**Comment by msailes** [comment]
Can you try this instead?

```java
  @Override
  public Void handleRequest(CloudFormationCustomResourceEvent request, Context context) {
    log.info("Full request = {}", Json.asString(request));
  }
```

AWS Lambda processes some events before the are passed to the function handler method. `CloudFormationCustomResourceEvent` is one of them. The library [aws-lambda-java-serialization](https://github.com/aws/aws-lambda-java-libs/tree/master/aws-lambda-java-serialization) is where this happens.

If you're interested you can see the code 

https://github.com/aws/aws-lambda-java-libs/blob/3ab22135a35c7ae2c52e062acf6cf5202af434a4/aws-lambda-java-serialization/src/main/java/com/amazonaws/services/lambda/runtime/serialization/events/mixins/CloudFormationCustomResourceEventMixin.java#L24

**Comment by Gtofig** [comment]
Ah, ok, didn't realize there was some special handling of these events. Thanks, looks like this can be closed then. Out of curiosity, why is this handled like that and not just by annotating the data model itself with `JsonProperty`?

**Comment by msailes** [comment]
In this case it was the case of an attribute, in other cases it's more complex. I'm glad we could get your problem fixed.
