### ISSUE TITLE
aws-lambda-java-log4j2 doesn't support RequestId output

### ISSUE THREAD

**Issue by DaichiUeura** [aws/aws-lambda-java-libs#26]
Since AWS Lambda execution environment seems to expect the log4j's MDC class to pass a RequestId, RequestId is not be able to be recorded in CloudWatch if aws-lambda-java-log4j2 is used in a Lambda application.

When I tried aws-lambda-java-log4j2 around August, the following error message appeared in CloudWatch.
`Unable to load the log4j's MDC class, customer cannot see RequestId from MDC`

Any plan to support RequestId output?

**Comment by asuresh8** [comment]
RequestId did work despite that error message, and that error message has since been fixed.

**Comment by DaichiUeura** [comment]
It worked. Thank you.
