### ISSUE TITLE
Maven aws-lambda-java-events link not available

### ISSUE THREAD

**Issue by SwapnilKhante** [aws/aws-lambda-java-libs#267]
hi Team,

Maven link is not available for following dependency version

<dependency>
    <groupId>com.amazonaws</groupId>
    <artifactId>aws-lambda-java-events</artifactId>
    <version>3.1.0</version>
</dependency>

https://mvnrepository.com/artifact/com.amazonaws/aws-lambda-java-events/3.1.0

Can you please share location to download the sources for this dependency ?

**Comment by msailes** [comment]
Hi @SwapnilKhante, 

You can find them here https://repo1.maven.org/maven2/com/amazonaws/aws-lambda-java-events/3.1.0/

Thanks,
