### ISSUE TITLE
Lambda RequestHandler does not return nulls in response

### ISSUE THREAD

**Issue by SamStephens** [aws/aws-lambda-java-libs#281]
I have a Java Lambda that I wish to sometimes populate a key with a string value, and sometimes set it to null, to indicate that the key is not meaningful in this case.

However if I set a key to have the value null, that key is not included in the output. Repro code:

```
public class App implements RequestHandler<Map<String, Object>, Map<String, Object>> {
    @Override
    public Map<String, Object> handleRequest(Map<String, Object> input, Context context) {
        HashMap<String, Object> output = new HashMap<>();
        output.put("nonNulllKey", "nonNull");
        output.put("nullKey", null);
        return output;
    }
}
```

If you create a Lambda with this code, the result will include nonNulllKey, but not nullKey.

I've checked this is not a Lambda limitation by returning a `None` value in Python and confirming I can see the key with the null value in the response.

**Comment by msailes** [comment]
Hi @SamStephens,

The Java serialisation code and configuration can be found here [JacksonFactory.java](https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-serialization/src/main/java/com/amazonaws/services/lambda/runtime/serialization/factories/JacksonFactory.java#L92). It is configured to ignore nulls.

Changing this behaviour would likely effect another user. 

With the [next major version of the events library](https://github.com/aws/aws-lambda-java-libs/issues/282) customers will have the ability to bring their own serialiser. This would give you the ability to configure the behaviour to match that of the Python runtime.

Mark

**Comment by SamStephens** [comment]
@msailes sorry I didn't see this earlier. This is a nasty limitation, it prevents Java users from returning null values. I understand the fear of backwards incompatible changes, but I'd ask the in the next major version, the default configuration retains null keys, as the distinction between a missing key and a null key can be a semantically important one.
