### ISSUE TITLE
What object to use as a response for format 2.0, when working with AWS Lambda authorizers for HTTP APIs?

### ISSUE THREAD

**Issue by MihaiBogdanEugen** [aws/aws-lambda-java-libs#294]
What object to use as a response for format 2.0, when working with AWS Lambda authorizers for HTTP APIs?

I see I have the `APIGatewayV2CustomAuthorizerEvent` for the request, but what can I use for the response - the simple response, format 2.0?

**Comment by msailes** [comment]
Hi Bogdan,

You can respond in one of two ways as described in the [dev guide](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-lambda-authorizer.html). Either with a [simple response](https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/SimpleIAMPolicyResponse.java) or an [IAM Policy](https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/IamPolicyResponse.java).

Hope this helps,

Mark

**Comment by MihaiBogdanEugen** [comment]
Hi Mark,

I'm only curious if there are any dedicated such Pojo objects or do I have to write my own. Maybe I'll open a PR...

Best,
Bogdan

**Comment by msailes** [comment]
You can use either the [SimpleIAMPolicyResponse.java](https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/SimpleIAMPolicyResponse.java) or [IamPolicyResponse.java](https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/IamPolicyResponse.java)

**Comment by MihaiBogdanEugen** [comment]
Perfect, this is what I was after. Thanks!
