### ISSUE TITLE
aws-lambda-java-log4j2 - JsonTemplateLayout Not Working In Cloudwatch

### ISSUE THREAD

**Issue by Jpk518** [aws/aws-lambda-java-libs#303]
Hi, I am trying to use the `JsonTemplateLayout [1]` as the layout for my `aws-lambda-java-log4j2` implementation but am getting the following error showing up as a cloudwatch event, and then subsequent logs are not formatted:

`main ERROR Lambda contains an invalid element or attribute "JsonTemplateLayout"`

Below is the log4j2.xml configuration I have set up. When using this exact configuration with `PatternLayout [2]` or the deprecated `JsonLayout [3]` it works as expected with properly formatted cloudwatch events. Additionally when running code locally with the below configuration, it outputs proper JsonTemplateLayout formatted events in console.

```
<?xml version="1.0" encoding="UTF-8"?>
<Configuration packages="com.amazonaws.services.lambda.runtime.log4j2" status="trace">
    <Appenders>
        <Lambda name="Lambda">
            <JsonTemplateLayout eventTemplateUri="classpath:EcsLayout.json"/>
        </Lambda>
    </Appenders>
    <Loggers>
        <Root level="info">
            <AppenderRef ref="Lambda" />
        </Root>
        <Logger name="software.amazon.awssdk" level="WARN" />
        <Logger name="software.amazon.awssdk.request" level="DEBUG" />
    </Loggers>
</Configuration>
```

The only difference that I found between these layouts, are that the layouts that did work are included in the log4j dependencies that are packaged in `com.amazonaws:aws-lambda-java-log4j2:1.5.1 [4]`, whereas JsonTemplateLayout must be added as a separate package `org.apache.logging.log4j:log4j-layout-template-json:2.17.1`

Would there be any way to resolve this issue or is this an internal limitation with the package, thanks.

[1] https://logging.apache.org/log4j/2.x/manual/json-template-layout.html
[2] https://logging.apache.org/log4j/2.x/manual/layouts.html#PatternLayout
[3] https://logging.apache.org/log4j/2.x/manual/layouts.html#JSONLayout
[4] https://mvnrepository.com/artifact/com.amazonaws/aws-lambda-java-log4j2/1.5.1

**Comment by orozcoadrian** [comment]
I made a similar upgrade recently, using `aws-lambda-powertools-java`. One thing I noticed was the removal of `packages=".."` from `<Configuration` in their sample config file. I'd suggest trying that.
https://github.com/awslabs/aws-lambda-powertools-java/pull/670/files

**Comment by Jpk518** [comment]
@orozcoadrian That change made it work like magic, thanks!
