### ISSUE TITLE
Cookies in APIGatewayProxyRequestEvent

### ISSUE THREAD

**Issue by ehrlichja** [aws/aws-lambda-java-libs#308]
In `APIGatewayProxyRequestEvent`, I see that there is no attribute for `cookies`.  In practice cookies do not show up in the `headers` attribute and the only way I can get them is by deserializing the proxy event manually. Should we add it?

**Comment by msailes** [comment]
There are two version of the API Gateway proxy event, v1 and v2. The first version doesn't have `cookies` as a top level attribute whereas v2 does.

https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/APIGatewayV2HTTPEvent.java

From the developer guide - https://docs.aws.amazon.com/lambda/latest/dg/services-apigateway.html

Mark

**Comment by ehrlichja** [comment]
Thanks. I hadn't realized there are is a different class for the new version.
