### ISSUE TITLE
Support for deserialization of SNS event inside SQS Message

### ISSUE THREAD

**Issue by onyxraven** [aws/aws-lambda-java-libs#317]
It would be great to have a well supported method of deserializing the SNS message that is within the SQS message when an SQS queue subscribes to an SNS topic.

I would expect this to be a util, with a function signature that looks something like

```
SNSEvent.SNS getEmbeddedSns(SQSEvent.SQSMessage event)
```

Currently there's not an obvious way to use the existing SNS class in this way. The Jackson deserializer the runtime uses makes a lot of customizations, and I'm not comfortable reaching inside the serialization package for this as it looks to be more of an internal package dedicated to the runtime interface.

Unless there's a well supported way to get at this already?

**Comment by msailes** [comment]
Hi @onyxraven,

The Lambda Powertools for Java library has serialization support for similar use cases. I've not tried this exact one myself.

https://awslabs.github.io/aws-lambda-powertools-java/utilities/serialization/#easy-deserialization

If it doesn't work, I think it would be a good addition to that library.

**Comment by onyxraven** [comment]
Thanks for that! looks like there may be some opportunity there, which I'll dig into. Its not in the 'out of the box' feature set. But, thats probably the right library to add this to, and I'll move this request over there once I check it out.
