### ISSUE TITLE
No Event for CodePipeline

### ISSUE THREAD

**Issue by knizami** [aws/aws-lambda-java-libs#32]
Are CodePipeline events supported for AWS Lambda?  When calling a Lambda function from CodePipeline, we were unable to define a CodePipelineEvent ourself that would work.  There are also no examples to be found on the internet.

**Comment by oharaandrew314** [comment]
Dup of #16

**Comment by carlzogh** [comment]
Closing as duplicate of https://github.com/aws/aws-lambda-java-libs/issues/16
