### ISSUE TITLE
Add HTTP/2 trailers to ApplicationLoadBalancerResponseEvent

### ISSUE THREAD

**Issue by shennenkampnr** [aws/aws-lambda-java-libs#324]
Some clients sending requests over HTTP/2 expect trailing headers to be sent for successful responses. However, the current implementation of the [ApplicationLoadBalancerResponseEvent](https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/ApplicationLoadBalancerResponseEvent.java) currently has no field for HTTP/2 trailing headers. 

Would it be possible to add a settable `trailers` field to the ApplicationLoadBalancerResponseEvent, and send those as trailers from the ALB?

**Comment by msailes** [comment]
Hi @shennenkampnr,

This is not yet supported with the integration of ALB and Lambda.

I would suggest that you use the console to [submit your suggestion](https://aws.amazon.com/premiumsupport/knowledge-center/send-feedback-aws/).

**Comment by shennenkampnr** [comment]
Will do, thank you
