### ISSUE TITLE
domainPrefix is missing from request context ?

### ISSUE THREAD

**Issue by vedrax-admin** [aws/aws-lambda-java-libs#330]
In JS we can access the domainPrefix by doing that 

`const prefix = event.requestContext.domainPrefix;`

That way I can get the subdomain of the request as a string (e.g. **subdomain**.my-domain.com)

Why we won't have a similar solution in java. Something like

`String subdomain = event.getRequestContext().getDomainPrefix();`

Thanks

**Comment by msailes** [comment]
Hi @vedrax-admin,

I assume you're talking about an integration with API Gateway. If you're using [payload v2](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html#http-api-develop-integrations-lambda.proxy-format) (the default) then you can use the [APIGatewayV2HTTPEvent.java](https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/APIGatewayV2HTTPEvent.java)

This has `domainPrefix` within the `requestContext`

Mark

**Comment by vedrax-admin** [comment]
thanks
