### ISSUE TITLE
Add body and queryString fields inside the CloudfrontEvent request class

### ISSUE THREAD

**Issue by mhan00** [aws/aws-lambda-java-libs#353]
Hey team,
Recently I have been using CloudFrontEvent in Java package to build my lambda function but unable to access the body and queryString of the request due to the missing fields of body and queryString in Java. I noticed the CloudFrontEvent in both Node.js and Python packages have defined body and queryString fields. Can we update the CloudFrontEvent in Java package with fields of body and queryString involved?

**Comment by msailes** [comment]
Hi @mhan00,

I just wanted to check, are you using this to build a Lambda@Edge function?

Thanks,

Mark

**Comment by mhan00** [comment]
Hey Mark,
Thanks for reaching out. Yes, I m planning to use this package for lambda@edge function. But It seems like lambda@edge only supports for the runtime of python and node.js at this moment. Probably it's better to add those fields into the cloudfront package when lambda@edge function starts to support for Java.

**Comment by msailes** [comment]
I agree, I'll close this issue for now.
