### ISSUE TITLE
The new log4j2.xml file Configuration xml element parameter packages is wrong

### ISSUE THREAD

**Issue by Sylistron** [aws/aws-lambda-java-libs#36]
Currently, it points to "com.amazonaws.services.lambda.runtime.log4j2.LambdaAppender" which is not a package - it's a class.

The Configuration element needs to look like this:
<Configuration packages="com.amazonaws.services.lambda.runtime.log4j2">

**Comment by alez007** [comment]
like what ?

**Comment by asuresh8** [comment]
I have been using that configuration in production for several months and have had no issue. It's clear that the configuration is not "wrong". That said, if there is a better way to configure this, please reopen this issue and post that configuration here.

**Comment by Sylistron** [comment]
@alez007 Whoops - apparently the XML got stripped.  The packages attribute should read **com.amazonaws.services.lambda.runtime.log4j2**

Like so:

`<Configuration packages="com.amazonaws.services.lambda.runtime.log4j2">`
