### ISSUE TITLE
APIGatewayProxyResponseEvent.toString() broken

### ISSUE THREAD

**Issue by rudpot** [aws/aws-lambda-java-libs#362]
* APIGatewayProxyResponseEvent.toString() should return value for isBase64Encoded - as seen [here](https://github.com/aws/aws-lambda-java-libs/blob/311f97cc47b414633c62ee96d9df3e8404e14d69/aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/APIGatewayProxyResponseEvent.java#L153-L166) it does not

* APIGatewayProxyResponseEvent.toString() should return a properly formatted JSON style object. Currently headers (and probably multi-value headers, didn't test that) are displayed in "A=B, ..." format instead of "A: B, ..." format. Also string entries are not quoted, i.e. `{statusCode: 200, headers: {}}` should read `{"statusCode": 200, "headers": {}}`

**Comment by msailes** [comment]
The `APIGatewayProxyResponseEvent` will have the correct `toString()` method in the next major version release.

You can see the implementation on the [events-v4-serialization-v2](https://github.com/aws/aws-lambda-java-libs/blob/events-v4-serialization-v2/aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/apigateway/APIGatewayProxyRequestEvent.java) branch.

The `APIGatewayProxyResponseEvent` `toString()` method isn't meant to return a JSON formatted string. It returns a string representation of the object for testing, logging and debugging purposes.

**Comment by smirnoal** [comment]
closing
