### ISSUE TITLE
Release notes?

### ISSUE THREAD

**Issue by raupachz** [aws/aws-lambda-java-libs#37]
Hello there,

just found out there is a new version of aws-lambda-java-core: 1.2.0. 

Unfortunately I was missing a release tag and some release notes. Only the commit 36747fc8f24e257c31fc722a0ab5c698aa15553d has the information what was changed. Maybe we can have some kind of release notes and tagging? 

We don't want to brake things while upgrading to a new version. A short info what was changed would definitely help.

keep up the good work!

kind regards
Björn

**Comment by carlzogh** [comment]
Hey @raupachz, we've just added release notes for each of the libraries in this project - thanks for the suggestion. 

You can find those here:
- [aws-lambda-java-core](https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-core/RELEASE.CHANGELOG.md)
- [aws-lambda-java-events](https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-events/RELEASE.CHANGELOG.md)
- [aws-lambda-java-log4j](https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-log4j/RELEASE.CHANGELOG.md)
- [aws-lambda-java-log4j2](https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-log4j2/RELEASE.CHANGELOG.md)
