### ISSUE TITLE
Update Log4J2 Version

### ISSUE THREAD

**Issue by feinstein** [aws/aws-lambda-java-libs#38]
`Log4j2` is currently on version `2.10.0` and this library is still referencing version `2.8.2`. 

Please update the library.

**Comment by carlzogh** [comment]
Hey @feinstein - Log4j dependencies have been updated to `2.13.2` as part of `aws-lambda-java-log4j2` version `1.2.0`.

**Comment by feinstein** [comment]
Thanks, but seriously you guys need to rethink your worfklow. It took 2 years and a half to update a library reference. 

This is specially troublesome as "Using Components with Known Vulnerabilities" is the OWASP 9th most security risk.
