### ISSUE TITLE
SnapStart Support 

### ISSUE THREAD

**Issue by softprops** [aws/aws-lambda-java-libs#380]
https://aws.amazon.com/blogs/compute/reducing-java-cold-starts-on-aws-lambda-functions-with-snapstart/

Is it possible to add this new lambda feature to the lambda runtime api client?

**Comment by msailes** [comment]
Hi @softprops,

Could you give more detail regarding what you would like to see added?

**Comment by smirnoal** [comment]
I believe SnapStart is only supported for java11 managed runtime

**Comment by softprops** [comment]
That’s my understanding as well based on what I’ve read so far. I’ve recently upgraded to java 17 (thanks @msailes for the aws java 17 layer project). I’m loving java 17 and would like to not have to give that up and have to down grade just to get this lambda snapstart benefit.

the docs mentioned it’s implemented in the runtime so I’m presuming that means in the client that handles the lambda runtime api requests. 

Does the official java11 lambda runtime use the same runtime api client as the one in this project? If so I may get this for free and I can close out this issue.

**Comment by jam01** [comment]
Did I misread something, or there's no answer to the original question...? @softprops @msailes or is this addressed somewhere else?

**Comment by msailes** [comment]
There is no change required in this project for SnapStart.

**Comment by softprops** [comment]
Awesome! to clarify, should I expect snapstart should work out of the box for those using  a provided runtime  using this projects client as a handler executor and corretto as the jvm?

**Comment by msailes** [comment]
SnapStart is only available for Java 11.

**Comment by baldram** [comment]
> SnapStart is only available for Java 11.

@msailes Is there any timeline for when the official Java 17 runtime with the SnapStart support might be available 
(like next quarter or end of the year, or later)?

**Comment by msailes** [comment]
We are continuing to work on Java 17 support, but don't currently have a timeline we can share.
