### ISSUE TITLE
The field "records" in SQSEvent should be renamed to "Records"

### ISSUE THREAD

**Issue by desp0916** [aws/aws-lambda-java-libs#392]
As per the sample code: [Sample Amazon SQS function code](https://docs.aws.amazon.com/lambda/latest/dg/with-sqs-create-package.html#with-sqs-example-deployment-pkg-java):

``` java
package example;

import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.RequestHandler;
import com.amazonaws.services.lambda.runtime.events.SQSEvent;
import com.amazonaws.services.lambda.runtime.events.SQSEvent.SQSMessage;

public class Handler implements RequestHandler<SQSEvent, Void>{
    @Override
    public Void handleRequest(SQSEvent event, Context context)
    {
        for(SQSMessage msg : event.getRecords()){
            System.out.println(new String(msg.getBody()));
        }
        return null;
    }
}
```

The field "[records](https://github.com/aws/aws-lambda-java-libs/blob/main/aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/SQSEvent.java#L19)" in [SQSEvent](https://github.com/aws/aws-lambda-java-libs/blob/main/aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/SQSEvent.java) should be renamed to "Records", or `SQSEvent` object cannot be deserialized correctly and `event.getRecords()` in the sample code will throw `NullPointerException`.

**Comment by msailes** [comment]
Hi Gary,

Can you tell me more about how you are deserializing the SQSEvent? Lambda uses a custom ObjectMapper so it might well be different to yours if you're using the default one.

**Comment by desp0916** [comment]
Sorry, it is my fault. This issue occurs after I folIow the instructions on [AWS Distro for OpenTelemetry Lambda Support For Java](https://aws-otel.github.io/docs/getting-started/lambda/lambda-java#enable-auto-instrumentation-for-your-lambda-function) to add a layer (`arn:aws:lambda:ap-northeast-1:901920570463:layer:aws-otel-java-wrapper-amd64-ver-1-20-1:3`) and an enviroment variable (`AWS_LAMBDA_EXEC_WRAPPER=/opt/otel-handler`).  

I created a Lambda function:

``` java
package com.example;

import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.RequestHandler;
import com.amazonaws.services.lambda.runtime.events.SQSEvent;
import com.amazonaws.services.lambda.runtime.events.SQSEvent.SQSMessage;

public class Handler implements RequestHandler<SQSEvent, Void> {

	@Override
	public Void handleRequest(SQSEvent event, Context context) {
		for (final SQSMessage msg : event.getRecords()) {
			System.out.println(new String(msg.getBody()));
		}
		return null;
	}

}
```
then use the following SQS test event to test this Lambda function:

``` json
{
  "Records": [
    {
      "messageId": "19dd0b57-b21e-4ac1-bd88-01bbb068cb78",
      "receiptHandle": "MessageReceiptHandle",
      "body": "Hello from SQS!",
      "attributes": {
        "ApproximateReceiveCount": "1",
        "SentTimestamp": "1523232000000",
        "SenderId": "123456789012",
        "ApproximateFirstReceiveTimestamp": "1523232000001"
      },
      "messageAttributes": {},
      "md5OfBody": "{{{md5_of_body}}}",
      "eventSource": "aws:sqs",
      "eventSourceARN": "arn:aws:sqs:us-east-1:123456789012:MyQueue",
      "awsRegion": "us-east-1"
    }
  ]
}
```
the execution log:

```
{
  "errorMessage": "java.lang.NullPointerException",
  "errorType": "java.lang.NullPointerException",
  "stackTrace": [
    "com.example.Handler.handleRequest(Handler.java:12)",
    "java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)",
    "java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)",
    "java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)",
    "java.base/java.lang.reflect.Method.invoke(Unknown Source)",
    "io.opentelemetry.instrumentation.awslambdaevents.v2_2.TracingRequestWrapperBase.doHandleRequest(TracingRequestWrapperBase.java:66)",
    "io.opentelemetry.instrumentation.awslambdacore.v1_0.TracingRequestHandler.handleRequest(TracingRequestHandler.java:79)"
  ]
}
```

If I removed the layer and the environment variable, everything works fine. So this issue could be closed.

**Comment by willarmiros** [comment]
Hi @desp0916 - can you open this issue on https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues? This is a bug in the OTel Lambda instrumentation if it's causing a NPE.

**Comment by desp0916** [comment]
@willarmiros OK. I've created [an new issue](https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/7517) there.
