### ISSUE TITLE
scheduled event

### ISSUE THREAD

**Issue by brackxm** [aws/aws-lambda-java-libs#4]
Please add a ScheduledEvent.

**Comment by bmoffatt** [comment]
Now tracking issue internally

**Comment by djhworld** [comment]
:+1:

**Comment by otterley** [comment]
@bmoffatt any updates?

**Comment by asuresh8** [comment]
Working on adding in a bunch of new events over the next few weeks. Stay tuned.

**Comment by brackxm** [comment]
ScheduledEvent is available in 2.0
