### ISSUE TITLE
Environment variable different when SnapStart is enabled

### ISSUE THREAD

**Issue by ArtyomGabeev** [aws/aws-lambda-java-libs#402]
Hi,

I'm not sure this a correct place to ask this question.
I was evaluating SnapStart feature for Java based Lambda with Elastic APM.

I noticed, that published version with SnapStart enabled missing AWS_LAMBDA_LOG_STREAM_NAME environment variable.

This variable used by Elastic java agent in order to differentiate Lambda instances, here is a ref:
https://github.com/elastic/apm-agent-java/blob/main/apm-agent-core/src/main/java/co/elastic/apm/agent/impl/metadata/ServiceFactory.java#L52

Is there any particular reason why AWS_LAMBDA_LOG_STREAM_NAME is not propagated? 
If yes, what is the recommended way to distinguish Lambda instances within function?

**Comment by smirnoal** [comment]
Hi Artyom,
confirming this behaviour. For SnapStart the runtime is initialized and then a snapshot is taken. After the snapshot is restored, the log stream is different, and there is no way it can be configured in an environment variable of already running process

**Comment by ArtyomGabeev** [comment]
Hi, @smirnoal 
I see the point now,
Will we able to get log stream name from the context object passed to handler class? 
Looking at com.amazonaws.services.lambda.runtime.Context , log stream name is exposed.

Thanks,
Artyom

**Comment by ArtyomGabeev** [comment]
Answering previous question:
- after snapshot restore, context.getLogStreamName returns null.

Please confirm, that there are no plans to inject logStreamName via LambdaContext object for SnapStart enabled published versions, and I will close this issue.

**Comment by smirnoal** [comment]
No, the Context object is a shortcut to read environment variable: https://github.com/aws/aws-lambda-java-libs/blob/3d6fb0ebbcfbfab5a45449d1a1c2a412c87dae80/aws-lambda-java-runtime-interface-client/src/main/java/com/amazonaws/services/lambda/runtime/api/client/EventHandlerLoader.java#L885

**Comment by ArtyomGabeev** [comment]
@smirnoal , thank you, I'm closing this issue.
