### ISSUE TITLE
Simulate AWS runtime environment for lambda in local run.

### ISSUE THREAD

**Issue by patton73** [aws/aws-lambda-java-libs#403]
Is there a way to simulate the AWS environment for lamba with RO filesystem and only writable /tmp?
I tried to add --read-only --tmpfs /tmp:rw options while launching lambda on my PC and i get some errors at start

Failed to load the native runtime interface client library aws-lambda-runtime-interface-client.glibc.so. Exception: /tmp/.aws-lambda-runtime-interface-client: /tmp/.aws-lambda-runtime-interface-client: failed to map segment from shared object
Failed to load the native runtime interface client library aws-lambda-runtime-interface-client.musl.so. Exception: /tmp/.aws-lambda-runtime-interface-client: /tmp/.aws-lambda-runtime-interface-client: failed to map segment from shared object

The complete command line is this one:

docker run --read-only --tmpfs /tmp:rw  -d -v ~/.aws-lambda-rie:/aws-lambda:rw -p 9000:8080 --entrypoint /aws-lambda/aws-lambda-rie IMAGE:VERSION /usr/bin/java --add-opens java.base/java.util=ALL-UNNAMED -cp './*' com.amazonaws.services.lambda.runtime.api.client.AWSLambda LAMBDACLASS::handleRequest

Where IMAGE,VERSION,LAMBDACLASS are specific parameter for the run. 

Any idea?
What i am doing wrong?

**Comment by patton73** [comment]
You are saying that this parameter --tmpfs /tmp:rw does not make /tmp writable? So how to do that?

**Comment by smirnoal** [comment]
apologies, I'm saying that the runtime is using /tmp to write some stuff on startup. Basing on the logs from your first message, these binaries either can't be read, or corrupted. Could you inspect `/tmp/.aws-lambda-runtime-interface-client` after the runtime is started to validate it has valid libraries? Unfortunately can't help you with the proper docker command
