### ISSUE TITLE
API Gateway ProxyRequestEvent and Context missing key value pairs

### ISSUE THREAD

**Issue by tauriello** [aws/aws-lambda-java-libs#41]
In the APIGatewayProxyRequestEvent pojo the key/value for '$context.requestTimeEpoch' ([Reference](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-mapping-template-reference.html)) does not exist. Also appears to be the same for '$context.requestTime'.

**Comment by tauriello** [comment]
In addition the key/value for '$context.authorizer' and '$context.authorizer.*' others as well.

**Comment by pradychin** [comment]
I am having the same issue.. seeing $context.requestTimeEpoch as blank...
How did you solve this issue?

**Comment by onema** [comment]
> NOTE: The following is by no means an answer to the question

The [aws-serverless-java-container-core](https://mvnrepository.com/artifact/com.amazonaws.serverless/aws-serverless-java-container-core) package has a `AwsProxyRequest`POJO that is serialized better than this library POJOs. I have been using it as a workaround and I have been able to get most of the information I need when using a custom authorizer with Cognito!

**Comment by carlzogh** [comment]
Hey @tauriello, support for API Gateway WebSocket API events was released in version `2.2.7` of the `aws-lambda-java-events` library as `APIGatewayV2ProxyRequest` and `APIGatewayV2ProxyResponse` events.

These V2 models include the fields you're looking for:
- [requestTime](https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/APIGatewayV2ProxyRequestEvent.java#L237)
- [requestTimeEpoch](https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/APIGatewayV2ProxyRequestEvent.java#L238)
- [authorizer](https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/APIGatewayV2ProxyRequestEvent.java#L225)
