### ISSUE TITLE
Failed to serialize CognitoUserPoolPreTokenGenerationEvent

### ISSUE THREAD

**Issue by NikolayMetchev** [aws/aws-lambda-java-libs#433]
Hello,
I am trying to use cognito and a java pre-token generation event lambda https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-pre-token-generation.html

I wrote a lambda and used the following class as my lambda definition: com.amazonaws.services.lambda.runtime.RequestHandler<com.amazonaws.services.lambda.runtime.events.CognitoUserPoolPreTokenGenerationEvent, com.amazonaws.services.lambda.runtime.events.CognitoUserPoolPreTokenGenerationEvent>

this doesn't seem to be able to parse the input at all and I get the following output in the logs:
```
CognitoUserPoolPreTokenGenerationEvent(request=CognitoUserPoolPreTokenGenerationEvent.Request(clientMetadata=null, groupConfiguration=CognitoUserPoolPreTokenGenerationEvent.GroupConfiguration(groupsToOverride=[us-east-1_IWxv0Zfr1_Test], iamRolesToOverride=[], preferredRole=null)), response=CognitoUserPoolPreTokenGenerationEvent.Response(claimsOverrideDetails=null))
```

If however I use `com.amazonaws.services.lambda.runtime.RequestStreamHandler` I do in fact see the correct input in the lambda log. Please help

**Comment by msailes** [comment]
If you change the method to <String, String> and log out the event. What does it look like?

Obviously please don't share any sensitive details.

**Comment by NikolayMetchev** [comment]
any news here?

**Comment by NikolayMetchev** [comment]
I have figured out what the problem is. The `toString()` method of CognitoUserPoolPreTokenGenerationEvent doesn't print out the object properly. It seems everything is working as expected.

**Comment by NikolayMetchev** [comment]
Can I get away with just a patch?

[Create_toString_methods_that_call_super_toString().patch](https://github.com/aws/aws-lambda-java-libs/files/12540559/Create_toString_methods_that_call_super_toString.patch)

**Comment by NikolayMetchev** [comment]
Looks like I managed to create a pull request.
