### ISSUE TITLE
Add support for Async RequestHandler

### ISSUE THREAD

**Issue by pendula95** [aws/aws-lambda-java-libs#44]
Is it possible to add support for Async Request Handler to support async buissnis logic implemented in lambda function.
Currently only sync request handler is available: 
aws-lambda-java-libs/aws-lambda-java-core/src/main/java/com/amazonaws/services/lambda/runtime/RequestHandler.java

This has already been requested here: 
[https://github.com/aws/aws-sdk-java/issues/1164](https://github.com/aws/aws-sdk-java/issues/1164)

If needed I would like to contribute to this solution.

**Comment by msailes** [comment]
Could you give an example of how this would be used?

Would you want the Lambda function to return early while work happens in the background?

**Comment by msailes** [comment]
Closing awaiting more information.

**Comment by natanfudge** [comment]
> Would you want the Lambda function to return early while work happens in the background?

The point is to avoid blocking a thread when responding to a request. 
I've detailed out the motivation in an MS painting:
![async programming for dummies](https://user-images.githubusercontent.com/25990014/168160102-23929cb4-e36c-4bf1-af2f-808475288bcb.png)

Kindly reopen this issue, async programming is a feature so basic it's integrated into all modern languages (Javascript, C#, Dart, Swift, Python, Ruby `async`, Go `chan`, Kotlin `suspend`)
Any method that expects to do IO work should be defined as async/suspend e.g. 
Kotlin:
```Kotlin
suspend fun Response handleRequest(request: Request) {
}
```
Java:
```Java
public Future<Response> handleRequest(request: Request) {
}
```

**Comment by msailes** [comment]
Each execution environment of a Lambda function only handle one request at once.

**Comment by natanfudge** [comment]
What does that mean? If two requests need to be met at the same time it starts 2 separate processes?

**Comment by natanfudge** [comment]
What does that mean? If two requests need to be met at the same time it starts 2 separate processes?
In NodeJs it documenately doesn't work that way:
> Node.js initialization

Node.js has a unique event loop model that causes its initialization behavior to be different from other runtimes. Specifically, Node.js uses a non-blocking I/O model that supports asynchronous operations. This model allows Node.js to perform efficiently for most workloads. For example, if a Node.js function makes a network call, that request may be designated as an asynchronous operation and placed into a callback queue. The function may continue to process other operations within the main call stack without getting blocked by waiting for the network call to return. Once the network call is returned, its callback is executed and then removed from the callback queue.

Some initialization tasks may run asynchronously. These asynchronous tasks are not guaranteed to complete execution prior to an invocation. For example, code that makes a network call to fetch a parameter from AWS Parameter Store may not be complete by the time Lambda executes the handler function. As a result, the variable may be null during an invocation. To avoid this, ensure that variables and other asynchronous code are fully initialized before continuing with the rest of the function’s core business logic.

**Comment by marksailes** [comment]
If a second invoke of a Lambda function is made before the first has finished a new execution environment will be created.

https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtime-environment.html

**Comment by natanfudge** [comment]
I see. As I don't see this model changing, there's no point for an EventHandler to be async.
