### ISSUE TITLE
Unable to upgrade with newer Jackson - conflicting `com.fasterxml.jackson.annotation.JsonFormat`

### ISSUE THREAD

**Issue by aleskiewicz** [aws/aws-lambda-java-libs#448]
Since release `1.1.3` , there is a risk of conflict with `jackson-annotations` jar. PR #445 has changed shading rules for selected list of Jackson annotations and now, some are exposed under original package name (see attached image).

 In our case, after upgrade to version `1.1.3` the app fails to start, because of missing `com.fasterxml.jackson.annotation.JsonFormat.Feature.READ_UNKNOWN_ENUM_VALUES_USING_DEFAULT_VALUE`. This feature switch is available since Jackson `2.15` . We are using Jackson `2.15.2`. Workaround for this issue is to include `jackson-annotations` before the `aws-lambda-java-serialization` dependency, so classloader first loads updated Jackson classes, but that's not the ideal way
```
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
        </dependency>
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-lambda-java-serialization</artifactId>
            <version>1.1.3</version>
        </dependency>
```

![image](https://github.com/aws/aws-lambda-java-libs/assets/3283086/d108b055-fd0f-4ad3-a03a-ade143c2b6ef)

![image](https://github.com/aws/aws-lambda-java-libs/assets/3283086/00c73d4b-5f28-4691-af5b-f5c660e26f25)

**Comment by mo7ty** [comment]
Hi!
Sorry to ask, might be a silly question, but why is Jackson shaded in `aws-lambda-java-serialization`?
Why not use it just as a dependency?

**Comment by smirnoal** [comment]
there are no silly question. all 3rd party deps in libraries are relocated to not clash with customers dependencies

**Comment by smirnoal** [comment]
1.1.4 has been released, which solves this issue, resolving

**Comment by aleskiewicz** [comment]
Now just a new base lambda image and ready to test on production ;) 

Thanks?

**Comment by hamidehsani54** [comment]
Run 
./gradlew dependencies

Make sure that all the jackson dependencies are same. 
If not modify it so that all dependencies looks the same. This version worked: 2.13.3
