### ISSUE TITLE
SNSEvent doesn't work properly

### ISSUE THREAD

**Issue by jonninja** [aws/aws-lambda-java-libs#45]
SNS Event doesn't appear to be parsed correctly, and as a result is unusable. As best I can tell, it is the result of incorrect case, as the "Records" and "records" are mismatched. Lambda parsing is opaque, so I'm not exactly sure how it's used, but when I define my own version of SNSEvent, things work fine.

**Comment by jschwartz73** [comment]
SQSEvent has the same problem.  com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "Records" 

To resolve, configure your ObjectMapper as follows:

ObjectMapper objectMapper = new ObjectMapper();
objectMapper.configure(MapperFeature.ACCEPT_CASE_INSENSITIVE_PROPERTIES, true);

**Comment by bmoffatt** [comment]
There's a behind-the-scenes object-mapper in the runtime that's allowing "Records" to be accepted. @jschwartz73 should work for local testing needs.

**Comment by drewish** [comment]
I also ran into this with an `SQSEvent`. My work around was to just skip the official classes and pass a `JsonNode` into the invoker.
