### ISSUE TITLE
Failed to deserialize DynamodbEvent.DynamodbStreamRecord#dynamodb

### ISSUE THREAD

**Issue by mo7ty** [aws/aws-lambda-java-libs#452]
When deserializing a `DynamodbEvent`, the contained `DynamodbEvent.DynamodbStreamRecord#dynamodb` (type: `StreamRecord`) is completely loaded: keys and new and old images (when present, obviously).

But when attempted to deserialize directly a `DynamodbEvent.DynamodbStreamRecord`, the contained `DynamodbEvent.DynamodbStreamRecord#dynamodb` (type: `StreamRecord`) is **NOT** loaded correctly.

Created demonstration test available at [Add test for `DynamodbEvent.DynamodbStreamRecord` load](https://github.com/mo7ty/aws-lambda-java-libs/commit/a6e2991f6bf49718c0eca17a08eaa9be52e72def):
  * Added [`EventLoaderTest#testLoadDynamodbStreamRecord()`](https://github.com/mo7ty/aws-lambda-java-libs/commit/a6e2991f6bf49718c0eca17a08eaa9be52e72def#diff-46ce264a2374bf6be6602d1f35ac3e89719b50bc7e11ed5acefc34e791a8eaffR189-R205) fails.

Why? What am I missing?

**Comment by mo7ty** [comment]
Answering my own question...

> *Why?*

Because the `DynamodbEvent.DynamodbStreamRecord` nested classes are not registered in `LambdaEventSerializers#NESTED_CLASS_MAP`.

Refer to [Add support for DynamodbEvent.DynamodbStreamRecord serialization #455](https://github.com/aws/aws-lambda-java-libs/pull/455)

**Comment by mo7ty** [comment]
After [Add support for DynamodbEvent.DynamodbStreamRecord serialization #455](https://github.com/aws/aws-lambda-java-libs/pull/455) included in [aws-lambda-java-serialization v1.1..5](https://github.com/aws/aws-lambda-java-libs/blob/main/aws-lambda-java-serialization/RELEASE.CHANGELOG.md#december-1-2023), although everything works locally and all added tests pass successfully, when running in AWS Lambda (runtime Java17) the `DynamodbEvent.DynamodbStreamRecord#dynamodb` is not parsed correctly:

```json
{
    "eventID": "_Event::Id_",
    "awsRegion": "eu-west-1",
    "eventSourceARN": "arn:aws:dynamodb:eu-west-1:_AWS::Account_:table/_DDB::Table_/stream/_DDB::Stream::Id_",
    "eventVersion": "1.1",
    "eventSource": "aws:dynamodb",
    "eventName": "REMOVE",
    "userIdentity": null,
    "dynamodb": {
        "streamViewType": null,
        "sequenceNumber": null,
        "approximateCreationDateTime": null,
        "newImage": null,
        "keys": null,
        "oldImage": null,
        "sizeBytes": null
    }
}
```

> Why? What am I missing?

**Comment by smirnoal** [comment]
the new version has not been deployed with managed Lambda runtimes yet. Meantime, you can use either OCI deployment or [wrapper](https://docs.aws.amazon.com/lambda/latest/dg/runtimes-modify.html#runtime-wrapper) to package 1.1.5 along with your function

**Comment by mo7ty** [comment]
> the new version has not been deployed with managed Lambda runtimes yet. Meantime, you can use either OCI deployment or [wrapper](https://docs.aws.amazon.com/lambda/latest/dg/runtimes-modify.html#runtime-wrapper) to package 1.1.5 along with your function

Thanks @smirnoal

**Comment by mo7ty** [comment]
Hi @smirnoal!
Didn't had the chance yet to include this update in the pipeline - is planned to be included during 2024 Q2 maintenance.
From my side, consider this issue closed, as it is working locally.
