### ISSUE TITLE
isBase64Encoded field missing from APIGatewayProxyResponseEvent

### ISSUE THREAD

**Issue by dsilvasc** [aws/aws-lambda-java-libs#46]
The field `isBase64Encoded` from https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html#api-gateway-simple-proxy-for-lambda-output-format is not present in APIGatewayProxyResponseEvent.

It's present in the [AwsProxyResponse](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/model/AwsProxyResponse.java) class from https://github.com/awslabs/aws-serverless-java-container though -- also an Amazon project.  Maybe these two projects could share API Gateway data types?

**Comment by miere** [comment]
> Also, I miss the isBase64Encoded attribute on the request object too.
I've overlooked the request object. Indeed, the `isBase64Encoded` is there.
But, off course, the response object still misses this attribute.

**Comment by michaelwiles** [comment]
Please can this be merged...

**Comment by bmoffatt** [comment]
merged #48

**Comment by jchapelle** [comment]
I've juste created a lambda returning application/pdf data encoded as base64.
` APIGatewayProxyResponseEvent response = new APIGatewayProxyResponseEvent();
            response.setStatusCode(200);
            HashMap<String, String> headers = new HashMap();
            headers.put("Content-Type", "application/pdf");
            response.setHeaders(headers);
            response.setIsBase64Encoded(true);
            response.setBody(base64Document);`

In the api gateway logs, I cannot see anywhere isBase64Encoded in the response received from lambda. Where is it supposed to be set ?

My client keeps receiving response from api gateway as base64 encoded string. I would like the data to be sent as binary data.

The Accept header sent by my client contains "application/pdf" as the only one parameters and the mediaType in setting of the api gateway is also "application/pdf" (ven tried it with */*).

Could you help ?

**Comment by michaelwiles** [comment]
Try this:

https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-payload-encodings-configure-with-console.html
