### ISSUE TITLE
AWS documentation says LambdaLogger will default to the INFO log level, but it is actually defaulting to UNDEFINED

### ISSUE THREAD

**Issue by stefansundin** [aws/aws-lambda-java-libs#466]
The documentation on this page: https://docs.aws.amazon.com/lambda/latest/dg/java-logging.html#java-logging-advanced

> If you don't assign a level to your log output, Lambda will automatically assign it the level INFO.

But this does not seem to be true. I am getting `UNDEFINED` in my tests, as this code seems to reinforce:

https://github.com/aws/aws-lambda-java-libs/blob/3d8dfb66f3a852bf69618bd5f66222692f1f5a49/aws-lambda-java-core/src/main/java/com/amazonaws/services/lambda/runtime/logging/LogLevel.java#L6-L9

According to this code it seems like `UNDEFINED` is intended, so perhaps the docs should be updated.

Thanks.

**Comment by smirnoal** [comment]
this is fixed in versions 2.4.2 of RIC, which is already available in maven central. Managed runtime and OCI base images deployments are also scheduled

**Comment by smirnoal** [comment]
Closing the issue as the fix has been deployed recently. Feel free to reopen in case of further question
