### ISSUE TITLE
Why does amazon not support a unified naming standard for java libs?

### ISSUE THREAD

**Issue by patrickjamesbarry** [aws/aws-lambda-java-libs#474]
The aws java sdk decided to migrate away from com.amazon in favor of software.amazon.  This applies to artifact groupIds as well as package names.  However, it seems that repos like this one decided to stay with the old name. This makes it super hard for other devs to quickly look at a dependency tree and see if they have all v2 vs v1 dependencies.  Why does amazon not have a unified naming standard when it comes to identifying their artifacts?

Feature request: Pick one and standardize across all aws repos

**Comment by smirnoal** [comment]
This project is not related to AWS SDK and is not sharing common naming conventions with it
