### ISSUE TITLE
CognitoUserPoolPreTokenGenerationEvent Only supports V1 of the event

### ISSUE THREAD

**Issue by Neil3079** [aws/aws-lambda-java-libs#478]
I am looking to add some custom claims to an access token during the authorisation process following the instructions here https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-pre-token-generation.html.

There only seems to be support for the basic version of CognitoUserPoolPreTokenGenerationEvent. The advanced version with parameters to customise the access token seem to be missing?

Is it possible to add this event?

**Comment by NikolayMetchev** [comment]
this is now resolved
