### ISSUE TITLE
Compatibility in java versions

### ISSUE THREAD

**Issue by yuuresuzuki** [aws/aws-lambda-java-libs#486]
Hi

I migrate our project from java 8 to java 11.

We use aws-lambda-java-core and aws-lambda-java-log4j in our project.

So, I would like to know which version of aws-lambda-java-libs corresponds to which version of java

Thank you.

**Comment by smirnoal** [comment]
all artefacts in this repository are compiled with java8, so that they can be consumed in java11/17/21

**Comment by yuuresuzuki** [comment]
Thank you very much.
