### ISSUE TITLE
Add Support For CloudWatchEvent

### ISSUE THREAD

**Issue by inrix-adasgupta** [aws/aws-lambda-java-libs#57]
As EMR Events are now supported for Lambda (https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/EventTypes.html#emr_event_type), it'll be nice to have corresponding event(s) in aws-lambda-java-events.

Currently we can define a custom POJO to intercept it, but deserialization doesn't work for 'detail-type' parameter, as it seem Jackson annotations are not supported and 'detail-type' is not a valid member name to be used as-is.

**Comment by msailes** [comment]
Hi Abhishek Dasgupta,

All CloudWatch events follow the same schema. You can use the following event to handle this case.

https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/ScheduledEvent.java

Thanks,

Mark
