### ISSUE TITLE
Make Events derive from a common abstract type

### ISSUE THREAD

**Issue by jaferrando** [aws/aws-lambda-java-libs#59]
Use case: Create a lambda function that handles different event types

The handler class has to implement the RequestHandler interface with <T,String>, being T one of the event types. As those do not share a common ancestory type, we need to implement the handling of each event type as a separa te class, and hence a separate Lambda. Having a common ancestor type would allow to implement RequestHandler<LambdaEventAbstractType,String> and determine in the handler function the type of event by inspecting its class with event.getClass().
This would also be a more Object oriented design, with a group of closely related types having a common ancestor.
We can now do something similar by implementing RequestHandler<Object,String> but it is poorer design and too loose in terms of type control.

**Comment by jblacker** [comment]
This would be very helpful for creating base classes and shared logic between different lambda functions or multiple triggers to the same function.

**Comment by jainishshah17** [comment]
I am also looking for this feature. I want to trigger my lambda function with SQSEvent/CloudWatchLogs Event.

**Comment by simon1389** [comment]
any updates on this?

**Comment by msailes** [comment]
No, update. This may be considered in the future, but not at the moment.

**Comment by smirnoal** [comment]
which interface do you think would be useful to introduce? Also wanted to learn more about what would differentiate `LambdaEventAbstractType` from `Object`, usecases would be helpful. Thanks!

**Comment by smirnoal** [comment]
resolving this issue as not planned. I would not recommend the proposed pattern with `LambdaEventAbstractType` and making reflection api calls to determine the actual type during runtime, but rather use compile-time capabilities to detect possible errors earlier in the process.
