### ISSUE TITLE
Support for Multi-Value Headers and Query String Parameters

### ISSUE THREAD

**Issue by medinarrior** [aws/aws-lambda-java-libs#60]
API Gateway supports multiple headers and query string parameters that have the same name. Multi-value headers as well as single-value headers and parameters can be combined in the same requests and responses. For more information, see Input Format of a Lambda Function for Proxy Integration and Output Format of a Lambda Function for Proxy Integration.

https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html#apigateway-multivalue-headers-and-parameters

**Comment by tphokas** [comment]
New version released - https://repo.maven.apache.org/maven2/com/amazonaws/aws-lambda-java-events/2.2.3/
