### ISSUE TITLE
ConnectionId for API Gateway requests is missing

### ISSUE THREAD

**Issue by AntonRamashko** [aws/aws-lambda-java-libs#76]
As in code example from Node.js from [here](https://aws.amazon.com/ru/blogs/compute/announcing-websocket-apis-in-amazon-api-gateway/) connectionId is used to manage WebSocket sessions:
```javascript
exports.handler = function(event, context, callback) {
var deleteParams = {
    TableName: process.env.TABLE_NAME,
    Key: {
     connectionId: { S: event.requestContext.connectionId }
    }
};
```

Meanwhile Java class `com.amazonaws.services.lambda.runtime.events.APIGatewayProxyRequestEvent.ProxyRequestContext` doesn't have such field.

**Comment by PatrykGala** [comment]
I've used workaround:
```
public class ConnectHandler implements RequestHandler<Map<String, Object>, ApiGatewayResponse> {
    private static final Logger LOG = LogManager.getLogger(ConnectHandler.class);

    @Override
    public ApiGatewayResponse handleRequest(Map<String, Object> input, Context context) {
        String connectionId = extractConnectionId(input);
        LOG.info("connectionid: {}", connectionId);
        return ApiGatewayResponse.ok(connectionId);
    }

    private String extractConnectionId(Map<String, Object> input) {
        Map<String, Object> requestContext = (Map<String, Object>) input.get("requestContext");
        return (String) requestContext.get("connectionId");
    }
}
```

**Comment by lucasam** [comment]
I believe this PR #92 fixes this issue.
A new class https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/APIGatewayV2ProxyRequestEvent.java is created to handle APIGatewayV2 parameters

**Comment by carlzogh** [comment]
@lucasam [APIGatewayV2ProxyRequestEvent](https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/APIGatewayV2ProxyRequestEvent.java) was added in version `2.2.7`
