### ISSUE TITLE
CodeCommitEvent Record

### ISSUE THREAD

**Issue by vbellotto** [aws/aws-lambda-java-libs#78]
The CodeCommitEvent format when a lambda is triggred is: 

> {
>   "Records": [
>     {
>       "awsRegion": "us-east-1",
>       "codecommit": {
>         "references": [
>           {
>             "commit": "5c4ef1049f1d27deadbeeff313e0730018be182b",
>             "ref": "refs/heads/teste"
>           }
>         ]
>       },
>       "customData": "this is custom data",
>       "eventId": "5a824061-17ca-46a9-bbf9-114edeadbeef",
>       "eventName": "TriggerEventTest",
>       "eventPartNumber": 1,
>       "eventSource": "aws:codecommit",
>       "eventSourceARN": "arn:aws:codecommit:us-east-1:123456789012:my-repo",
>       "eventTime": "2016-01-01T23:59:59.000+0000",
>       "eventTotalParts": 1,
>       "eventTriggerConfigId": "5a824061-17ca-46a9-bbf9-114edeadbeef",
>       "eventTriggerName": "my-trigger",
>       "eventVersion": "1.0",
>       "userIdentityARN": "arn:aws:iam::123456789012:root"
>     }
>   ]
> }

There is no way to access the custom data because the field is missing in the CodeCommitEvent.Record, or should I do something diffent ?

**Comment by bmoffatt** [comment]
merged #79

**Comment by vbellotto** [comment]
> merged #79

Do you have a prediction of when will have a release with this changes ?
