### ISSUE TITLE
Cannot deserialize instance of `java.util.Date` out of VALUE_NUMBER_FLOAT token

### ISSUE THREAD

**Issue by dnellutla** [aws/aws-lambda-java-libs#81]
Using aws-lambda-java events version 2.2.4, When I try to deserialize the Kinesis Event to a Java Object , I get the above error. I have seen similar post in AWS forums it has said it is fixed but I am facing this issue.

com.amazonaws.services.lambda.runtime.events.KinesisEvent$KinesisEventRecord["kinesis"]->com.amazonaws.services.lambda.runtime.events.KinesisEvent$Record["approximateArrivalTimestamp"]): com.fasterxml.jackson.databind.exc.MismatchedInputException
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.util.Date` out of VALUE_NUMBER_FLOAT token

**Comment by yodiegogutierrez** [comment]
Hi,
Did you get a fix for this case?

Thanks

**Comment by dnellutla** [comment]
Yes, It was fixed.

**Comment by yodiegogutierrez** [comment]
Thanks, Could you please share the fix?

**Comment by jhg023** [comment]
@dnellutla What was the fix?

**Comment by dnellutla** [comment]
It was not a fix, please check the JSON payload that you are sending.

**Comment by dnellutla** [comment]
Which version are you using?

**Comment by jhg023** [comment]
I only asked because I was looking to answer a [StackOverflow question](https://stackoverflow.com/q/59163993/7294647) asked by someone else, but it didn't seem to be an issue of this library specifically.

**Comment by parlacom** [comment]
<jackson.version>2.10.3</jackson.version>

Issue still there

**Comment by msailes** [comment]
A number of events require specific serialization logic. This can be for various reasons. The [serialization](https://github.com/aws/aws-lambda-java-libs/tree/master/aws-lambda-java-serialization) library encapsulates this functionality.
