### ISSUE TITLE
What about ApplicationLoadBalancerEvent?

### ISSUE THREAD

**Issue by 0xNacho** [aws/aws-lambda-java-libs#82]
Hi there.

I'm using a lambda function to process requests from an Application Load Balancer.

I'm writing the lambda code using the latest JAVA SDK (2.2.5), but  I'm not able to find out which is the runtime event class to access to the request event.
There does not seem to be any ApplicationLoadBalancerEvent class in the following link:

https://github.com/aws/aws-lambda-java-libs/tree/master/aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events

Thanks!

**Comment by cdwhatcott** [comment]
Is anybody working on this? I've got a lambda I'm working on that will process ALB events. If nobody is currently adding this, I'd be glad to add it.

**Comment by carlzogh** [comment]
Hey @0xNacho and @cdwhatcott - Application Load Balancer Target Events have been added to the `aws-lambda-java-events` library and released as part of version `3.1.0`.

ref: https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-events/RELEASE.CHANGELOG.md

Thanks for bringing this up!
