### ISSUE TITLE
pom file missing xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"

### ISSUE THREAD

**Issue by kostaskougios** [aws/aws-lambda-java-libs#85]
Hi,

This causes issues to coursier. It can't parse the pom file. Maven and sbt doesn't seem to mind but coursier fails.

Thanks

**Comment by carlzogh** [comment]
This issue was fixed by https://github.com/aws/aws-lambda-java-libs/commit/389461af2141053b3614a928b8ba83306706eb4f which has been merged and released.
Please update your `aws-lambda-java-libs` dependencies to the latest available versions to get this fix.
