### ISSUE TITLE
Missing fields in APIGatewayProxyRequestEvent$RequestContext class

### ISSUE THREAD

**Issue by marcinczeczko** [aws/aws-lambda-java-libs#88]
Looks like `APIGatewayProxyRequestEvent$RequestContext` has missing following properties:
```
extendedRequestId
requestTime
protocol
requestTimeEpoch
```

**Comment by Clifnich** [comment]
And domainName as well.

**Comment by carlzogh** [comment]
Hey @marcinczeczko - WebSocket API fields were added and released as part of `aws-lambda-java-events` version `2.2.7` (ref. [APIGatewayV2ProxyRequestEvent](https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/APIGatewayV2ProxyRequestEvent.java)).
