### ISSUE TITLE
can't parse pom files missing xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" #1104

### ISSUE THREAD

**Issue by Pratibha2007** [aws/aws-lambda-java-libs#89]

**Comment by Pratibha2007** [comment]
[error] org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 107; The prefix "xsi" for attribute "xsi:schemaLocation" associated with an element type "project" is not bound.
[error] at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1239)
[error] at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
[error] at coursier.core.compatibility.package$.xmlParseSax(package.scala:64)
[error] at coursier.maven.MavenRepository$.parseRawPomSax(MavenRepository.scala:70)
[error] at coursier.maven.MavenRepository.$anonfun$findVersioning$1(MavenRepository.scala:332)

**Comment by carlzogh** [comment]
This issue was fixed by https://github.com/aws/aws-lambda-java-libs/commit/389461af2141053b3614a928b8ba83306706eb4f which has been merged and released.
Please update your `aws-lambda-java-libs` dependencies to the latest available versions to get this fix.
