### ISSUE TITLE
SQSEvent.eventSourceArn property name does not match event field name

### ISSUE THREAD

**Issue by mwunderl** [aws/aws-lambda-java-libs#91]
In the event from Lambda, the name of the field is `eventSourceARN`, not `eventSourceArn`.
`KinesisEvent` and `DynamoDB` event use the casing from the event.
Users referencing the event structure expect the property and field names to match.

See [aws-lambda-developer-guide/pull/126](https://github.com/awsdocs/aws-lambda-developer-guide/pull/126) for more information.

**Comment by srayhunter** [comment]
Has this issue been updated in the code yet? This is causing issues with deserializing the json message.

**Comment by msailes** [comment]
The json events which are sent to Lambda don't always map to Java objects. When they don't additional logic is added to do the mapping on the customers behalf. You can see how this happens in [serialization](https://github.com/aws/aws-lambda-java-libs/tree/master/aws-lambda-java-serialization). To test that your handler correctly handles a given event in json format I would advise you to use our [testing](https://github.com/aws/aws-lambda-java-libs/tree/master/aws-lambda-java-tests) project, which includes serialization support.
