### ISSUE TITLE
Firehose transformation example

### ISSUE THREAD

**Issue by namedgraph** [aws/aws-lambda-java-libs#95]
[Amazon Kinesis Data Firehose Data Transformation](https://docs.aws.amazon.com/firehose/latest/dev/data-transformation.html#lambda-blueprints) says
> Lambda blueprints are only available in the Node.js and Python languages. You can implement your own functions in other supported languages.

I think this section treats Java unfairly. You provide this whole Lambda SDK for Java yet cannot include a simple example? Even the handler signature is unclear, as you can see from questions on your own [support forum](https://forums.aws.amazon.com/thread.jspa?threadID=253590) as well as on [StackOverflow](https://stackoverflow.com/questions/51710546/kinesis-firehose-data-transformation-using-java).

Can you please include an example so Java developers do not feel forced to abandon their language of choice and/or google second-hand sites for scraps of information? Thanks.

**Comment by namedgraph** [comment]
I have open-source one lambda which does an XSLT transformation on Kinesis Firehose recors (which have to be XML, or JSON with additional processing):
https://github.com/AtomGraph/XSLTTransform

**Comment by msailes** [comment]
Hi Martynas,

We've passed on your feedback to the docs team. Thank you for posting a link to you own example, that's really useful for the community.

**Comment by mberchon** [comment]
Hello,

Given the fact that this page is the 1st hit on google while searching for:
`aws lambda firehose java github`

I believe there is still an issue

**Comment by msailes** [comment]
@mberchon Thanks for the feedback,

I've raised a PR to create a new module to contain examples functions for the less obvious use cases. I'll talk to the team on Monday and see what they think.

I've not tested the example yet, I'll try and do that next week. The KinesisAnalyticsInputPreprocessingResponse response object seems to have the required attributes even if the name isn't particularly helpful in the Firehose use case.

Hopefully this helps a little.

https://github.com/aws/aws-lambda-java-libs/pull/271/files

**Comment by namedgraph** [comment]
Maybe this lambda can serve as an example: https://github.com/AtomGraph/XSLTTransform

**Comment by mberchon** [comment]
@msailes Thx for the link, it helps

I learned that the lambda function has to implement RequestHandler[KinesisFirehoseEvent, KinesisAnalyticsInputPreprocessingResponse] instead of  RequestHandler[KinesisFirehoseEvent,String].

And it works :-)

Thx again,
Mathieu

**Comment by liumengkai** [comment]
@msailes thx! help me l lot.
