### ISSUE TITLE
log4j2: X-Ray trace id?

### ISSUE THREAD

**Issue by triptec** [aws/aws-lambda-java-libs#98]
Hello, is there any way to get the X-Ray trace id added to the log output?
Similar to %X{AWSRequestId} but something like %X{AWSXRayTraceId}?

**Comment by msailes** [comment]
Hi Andreas, 

You can find instructions on how to do this in the AWS X-Ray developer guide 

https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-java-configuration.html

Under the section 'Trace ID injection into logs'

Thanks,
