### ISSUE TITLE
Log handler exceptions with log4j2

### ISSUE THREAD

**Issue by everett1992** [aws/aws-lambda-java-libs#99]
I've asked this question on [stackoverflow] as well.

I've noticed that uncaught exceptions are not logged with the root logger. For instance this lambda logs "handler" with log4j2 but the thrown exception is logged with LambdaLogger, or just written to stdout.

```
private static final logger = LogManager.getLogger();
public void handler() {
  log.info("handler");
  throw new RuntimeException("error")
}
```
The logs for an invocation of this function include the log4j2 info message, but the exception is logged plainly, without requestid, timestamp, or `ERROR` marker.

```
2019-10-07 11:39:02 43db1f36-0570-4b58-adc6-5c92ea62a862 INFO Example - handler
java.lang.RuntimeException: error
	at Test.main(Test.java:3)
```

It's harder to find exceptions in logs because you can't grep for the request id or `ERROR`.
I don't want to wrap my handlers with try-catch-log-rethrow.

```
try {
  ...
} catch (Throwable t) {
  log.fatal(t);
  throw t;
}
```

If I did use try-catch-log-rethrow the exception would be logged once by log4j and once by the default logger. Can the aws-lambda-java-log4j2 handle logging handler exceptions? Is there a pattern other customers use here?

[here]: https://docs.aws.amazon.com/lambda/latest/dg/java-logging.html#java-logging-log4j2
[aws-lambda-java-log4j2]: https://github.com/aws/aws-lambda-java-libs/tree/master/aws-lambda-java-log4j2
[stackoverflow]: https://stackoverflow.com/questions/58275490/log-aws-lambda-handler-exceptions-with-log4j2-using-aws-lambda-java-log4j2

**Comment by msailes** [comment]
Hi Caleb,

No the Lambda runtime doesn’t redirect stderr and stdout to log4j.

The best thing to do, as you've done is to catch, log and then throw again.

**Comment by brianmaresca** [comment]
4 years later, do we still have to catch log and re throw? can the default logger be disabled
